export enum ActionArea {
  MOBILITY_AND_TRANSPORT = "Mobility and transport",
  BUILT_ENVIRONMENT = "Built environment",
  NATURE = "Nature",
  ADAPTATION = "Adaptation",
  ENERGY = "Energy",
}

export enum Country {
  ALBANIA = "Albania",
  UK = "United Kingdom",
  FRANCE = "France",
  GERMANY = "Germany",
  NETHERLANDS = "Netherlands",
  BELGIUM = "Belgium",
  BOSNIA_AND_HERZEGOVINA = "Bosnia and Herzegovina",
  BULGARIA = "Bulgaria",
  CROATIA = "Croatia",
  CYPRUS = "Cyprus",
  DENMARK = "Denmark",
  ESTONIA = "Estonia",
  FINLAND = "Finland",
  SWEDEN = "Sweden",
  NORWAY = "Norway",
  ICELAND = "Iceland",
  IRELAND = "Ireland",
  ISRAEL = "Israel",
  SPAIN = "Spain",
  ITALY = "Italy",
  AUSTRIA = "Austria",
  CZECH_REPUBLIC = "Czech Republic",
  LATVIA = "Latvia",
  LITHUANIA = "Lithuania",
  LUXEMBOURG = "Luxembourg",
  MALTA = "Malta",
  MONTENEGRO = "Montenegro",
  POLAND = "Poland",
  HUNGARY = "Hungary",
  ROMANIA = "Romania",
  SLOVAKIA = "Slovakia",
  SLOVENIA = "Slovenia",
  GREECE = "Greece",
  PORTUGAL = "Portugal",
  TURKEY = "Turkey",
}
