export enum ActionArea {
  MOBILITY_AND_TRANSPORT = "Mobility and transport",
  BUILT_ENVIRONMENT = "Built environment",
  NATURE = "Nature",
  ADAPTATION = "Adaptation",
  ENERGY = "Energy",
}

export enum Country {
  ALBANIA = "Albania",
  UK = "United Kingdom",
  FRANCE = "France",
  GERMANY = "Germany",
  NETHERLANDS = "Netherlands",
  BELGIUM = "Belgium",
  BOSNIA_AND_HERZEGOVINA = "Bosnia and Herzegovina",
  BULGARIA = "Bulgaria",
  CROATIA = "Croatia",
  CYPRUS = "Cyprus",
  DENMARK = "Denmark",
  ESTONIA = "Estonia",
  FINLAND = "Finland",
  SWEDEN = "Sweden",
  NORWAY = "Norway",
  ICELAND = "Iceland",
  IRELAND = "Ireland",
  ISRAEL = "Israel",
  SPAIN = "Spain",
  ITALY = "Italy",
  AUSTRIA = "Austria",
  CZECH_REPUBLIC = "Czech Republic",
  LATVIA = "Latvia",
  LITHUANIA = "Lithuania",
  LUXEMBOURG = "Luxembourg",
  MALTA = "Malta",
  MONTENEGRO = "Montenegro",
  POLAND = "Poland",
  HUNGARY = "Hungary",
  ROMANIA = "Romania",
  SLOVAKIA = "Slovakia",
  SLOVENIA = "Slovenia",
  GREECE = "Greece",
  PORTUGAL = "Portugal",
  TURKEY = "Turkey",
}

export enum SpatialFrame {
  AGRICULTURAL_AND_GREEN_AREAS = "Agricultural & green areas",
  AIR_TRANSPORT = "Air transport",
  BUSINESSES_AND_EMPLOYERS = "Businesses & Employers",
  BROWNFIELD = "Brownfield",
  CITY_WIDE = "City-wide",
  CULTURAL_TOURIST_SECTOR = "Cultural/Tourist sector",
  EDUCATIONAL_AND_RESEARCH_INSTITUTIONS = "Educational & Research Institutions",
  EU = "EU",
  GLOBAL = "Global",
  HOSPITAL = "Hospital",
  HARBOURS_AND_PORTS = "Harbours & Ports",
  HERITAGE_BUILDINGS = "Heritage buildings",
  HOUSING_COOPERATIVES_AND_HOUSING_ASSOCIATIONS = "Housing cooperatives & housing associations",
  INTER_CITY = "Inter-city",
  INTER_REGIONAL = "Inter-regional",
  LOW_INCOME_HOUSEHOLDS = "Low-income households",
  MUNICIPAL_LAND_BUILDINGS = "Municipal land/buildings",
  NATIONAL = "National",
  NON_RESIDENTIAL_BUILDINGS = "Non-residential buildings",
  PRIVATE_LAND = "Private land",
  PUBLIC_SPACE = "Public Space",
  REGIONAL_AND_PERI_URBAN = "Regional & Peri-urban",
  RESIDENTIAL_BUILDINGS = "Residential buildings",
  RIVERS = "Rivers",
  SITE_SPECIFIC = "Site-specific",
  STREETS_AND_HIGHWAYS = "Streets and Highways",
}
